apiVersion: v1
kind: Secret
metadata:
  name: ees-auth-secret
  {{- include "rtl-poc.targetNamespace" . | nindent 2 }}
stringData:
  EES_AUTH_CLIENT_ID: {{ .Values.rtl.EES_AUTH_CLIENT_ID }}
  EES_AUTH_CLIENT_SECRET: {{ .Values.rtl.EES_AUTH_CLIENT_SECRET }}
type: Opaque
